# -*- coding: utf-8 -*-
"""open_ended_genai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pXYATcEGka2wNW1Sc2xQCpcxCEgA1pNo
"""

!pip install -q langchain
!pip install -q langchain-community
!pip install -q chromadb
!pip install -q langchain.text_splitters
!pip install -q sentence-transformers
!pip install -q transformers
!pip install -q accelerate
!pip install -q bitsandbytes

college_text = """
The college library is open from 8 AM to 8 PM.

Minimum attendance required is 75%.

The placement office is located in Block B.

Computer Science department offers AI and ML specialization.

Students can apply for internships through the placement portal.

Semester exams are conducted twice a year.

The college cafeteria operates from 9 AM to 6 PM.
"""

with open("college_info.txt", "w") as f:
    f.write(college_text)

print("Dataset created successfully!")

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Load document
loader = TextLoader("college_info.txt")
documents = loader.load()

# Split into chunks
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

docs = text_splitter.split_documents(documents)

print("Number of chunks:", len(docs))

from langchain_community.embeddings import HuggingFaceEmbeddings

embedding = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embeddings model loaded!")

from langchain_community.vectorstores import Chroma

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embedding
)

print("Vector database created!")

from transformers import pipeline

llm_pipeline = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_new_tokens=100
)

print("LLM Loaded Successfully!")

def chatbot(query):

    # Retrieve relevant documents
    retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

    retrieved_docs = retriever.invoke(query)

    context = ""

    for doc in retrieved_docs:
        context += doc.page_content + "\n"

    # Create prompt
    prompt = f"""
    Answer the question based only on the context below.

    Context:
    {context}

    Question:
    {query}

    Answer:
    """

    # Generate answer
    response = llm_pipeline(prompt)

    return response[0]['generated_text']

query = "What is the attendance requirement?"

answer = chatbot(query)

print("Question:", query)
print("Answer:", answer)

while True:

    query = input("Ask a question: ")

    if query.lower() == "exit":
        break

    answer = chatbot(query)

    print("\nAnswer:", answer)
    print("-" * 50)

